version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  web:
    build: ./web
    image: web
    command: serve -s web/build -p 4001
    volumes:
      - .:/usr/src/app/
    networks:
      - app-net
    ports:
      - 4001:4001
    restart: unless-stopped

  backend:
    build: ./
    image: backend
    command: uvicorn main:app --host 0.0.0.0 --port 4000
    volumes:
      - .:/usr/src/app/
    networks:
      - app-net
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    networks:
      - app-net
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongo: