version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  backend:
    build: ./
    image: backend
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload
    volumes:
      - .:/usr/src/app/
    networks:
      - app-net
    ports:
      - 4000:4000
    depends_on:
      - mongo
    restart: unless-stopped
  
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - .env.dev
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    user: root
    links:
      - backend
    networks:
      - app-net
    ports:
      - 80:80
    depends_on:
      - backend