version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  backend:
    build: ./
    image: backend
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload
    volumes:
      - .:/usr/src/app/
    networks:
      - app-net
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    depends_on:
      - mongo
    restart: unless-stopped
  
  mongo:
    image: mongo
    networks:
      - app-net
    env_file:
      - ./.env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    user: root
    links:
      - backend
    networks:
      - app-net
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  mongo: